stages:
  #sprites_data:
    #cmd: tar -xf data/raw/sprites.tar -C data/raw/
    #deps:
      #- data/raw/sprites.tar
    #outs:
      #- data/raw/sprites

  ae_dense_train:
    cmd: python src/autoencoder/vanilla_model_dense.py
    deps:
      - ${pokemon_sprites.data_dir}
      - src/autoencoder/train.py
      - src/autoencoder/vanilla_model_dense.py
      - src/data/sprites.py
      - src/utils.py
    params:
      - autoencoder_dense
    outs:
      #- reports/autoencoder/dense/gen
      - reports/autoencoder/dense/gen.gif
    plots:
      - reports/autoencoder/dense/logs
    metrics:
      - reports/autoencoder/dense/logs.json:
          cache: false

  ae_conv_train:
    cmd: python src/autoencoder/vanilla_model_conv.py
    deps:
      - ${pokemon_sprites.data_dir}
      - src/autoencoder/train.py
      - src/autoencoder/vanilla_model_conv.py
      - src/data/sprites.py
      - src/utils.py
    params:
      - autoencoder_conv
    outs:
      #- reports/autoencoder/conv/gen
      - reports/autoencoder/conv/gen.gif
    plots:
      - reports/autoencoder/conv/logs
    metrics:
      - reports/autoencoder/conv/logs.json:
          cache: false