stages:

  train:
    foreach: ${autoencoders}
    do:
      cmd: >
        python src/autoencoder/train.py
        --encoder-type ${item.type}
        --decoder-type ${item.type}
        --ae-type ${item.model}
        --model-path ${item.model_path}
        --epochs ${epochs}
        --batch-size ${batch_size}
        --latent-size ${latent_size}
        --log-dir ${item.log_dir}
        --lr ${lr}
        --val-ratio ${val_ratio}
        --reg-rate ${item.reg_rate}
      deps:
        - ${pokemon_sprites.data_dir}
        - src/autoencoder/train.py
        - ${item.model_src}
        - ${item.encoder_src}
        - ${item.decoder_src}
        - src/data/sprites.py
        - src/utils.py
      outs:
        - ${item.model_path}
        - ${item.log_dir}/gen
        - ${item.log_dir}/results
        - ${item.log_dir}/summary.txt
      plots:
        - ${item.log_dir}/logs
      metrics:
        - ${item.log_dir}/logs.json