stages:
  ae_train:
    cmd: python src/autoencoder/train.py
    deps:
      - data/external/sprites
      - src/autoencoder
      - src/data
    outs:
      - reports/autoencoder/gen
    plots:
      - reports/autoencoder/logs
    metrics:
      - reports/autoencoder/logs.json