stages:
  sprites_data:
    cmd: tar -xf data/raw/sprites.tar -C data/raw/
    deps:
      - data/raw/sprites.tar
    outs:
      - data/raw/sprites

  ae_train:
    cmd: python src/autoencoder/vanilla_model.py
    deps:
      - ${pokemon_sprites.data_dir}
      #- data/external/sprites
      - src/autoencoder
      - src/data
      - src/utils.py
    params:
      - autoencoder
    outs:
      - reports/autoencoder/gen
      - reports/autoencoder/gen.gif
    plots:
      - reports/autoencoder/logs
    metrics:
      - reports/autoencoder/logs.json