stages:
  ae_train:
    cmd: python src/autoencoder/train.py
    deps:
      #- data/external/sprites
      - src/autoencoder
      - src/data
      - src/utils.py
    params:
      - autoencoder
    outs:
      - reports/autoencoder/gen
      - reports/autoencoder/gen.gif
    plots:
      - reports/autoencoder/logs
    metrics:
      - reports/autoencoder/logs.json