stages:
  sprites_data:
    cmd: tar -xzf data/raw/sprites.tar.gz -C data/raw/
    deps:
      - data/raw/sprites.tar.gz
    outs:
      - data/raw/sprites

  ae_train:
    cmd: python src/autoencoder/train.py
    deps:
      - ${autoencoder.data_dir}
      #- data/external/sprites
      - src/autoencoder
      - src/data
      - src/utils.py
    params:
      - autoencoder
    outs:
      - reports/autoencoder/gen
      - reports/autoencoder/gen.gif
    plots:
      - reports/autoencoder/logs
    metrics:
      - reports/autoencoder/logs.json