pokemon_sprites:
  input_shape: [3, 96, 96]
  resize_shape: [96,96]
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]
  data_dir: data/raw/sprites

vae_conv:
  latent_size: 16
  batch_size: 128
  train_kwargs:
    epochs: 200
    log_dir: reports/vae/conv

vae_dense:
  latent_size: 16
  batch_size: 128
  train_kwargs:
    epochs: 200
    log_dir: reports/vae/dense


autoencoder_dense:
  latent_size: 16
  batch_size: 128
  train_kwargs:
    epochs: 200
    log_dir: reports/autoencoder/dense

autoencoder_conv:
  latent_size: 16
  batch_size: 128
  train_kwargs:
    epochs: 200
    log_dir: reports/autoencoder/conv
