pokemon_sprites:
  input_shape: [3, 96, 96]
  resize_shape: [96,96]
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]
  data_dir: data/external/sprites

epochs: 500
latent_size: 16
batch_size: 256
lr: 0.001

autoencoders:

  vae_dense:
    type: dense
    model: vae
    log_dir: reports/vae/dense
    model_src: src/autoencoder/models/variational_model.py
    encoder_src: src/autoencoder/encoders/dense.py
    decoder_src: src/autoencoder/decoders/dense.py

  vae_conv:
    type: conv
    model: vae
    log_dir: reports/vae/conv
    model_src: src/autoencoder/models/variational_model.py
    encoder_src: src/autoencoder/encoders/conv.py
    decoder_src: src/autoencoder/decoders/conv.py

  ae_dense:
    type: dense
    model: ae
    log_dir: reports/ae/dense
    model_src: src/autoencoder/models/vanilla_model.py
    encoder_src: src/autoencoder/encoders/dense.py
    decoder_src: src/autoencoder/decoders/dense.py

  ae_conv:
    type: conv
    model: ae
    log_dir: reports/ae/conv
    model_src: src/autoencoder/models/vanilla_model.py
    encoder_src: src/autoencoder/encoders/conv.py
    decoder_src: src/autoencoder/decoders/conv.py
