# This is a basic workflow to help you get started with Actions

name: AE

# Controls when the action will run. 
on:
  push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted,gpu]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      repo_token: ${{ secrets.GITHUB_TOKEN }}
      SHOULD_TQDM: 0  # disables tqdm in 'src/train_ae.py'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: requirements
        run: pip install -r requirements.txt

      - name: pull_data
        run: |
          dvc pull data/raw/sprites.dvc

      - name: train_ae_dense
        run: |
          dvc pull train@ae_dense
          dvc repro train@ae_dense
          dvc push train@ae_dense

      - name: report_dense
        run: |
          scripts/autoencoder_report.sh autoencoder dense >> report.md
          cml-send-github-check report.md 


      - name: train_ae_conv
        run: |
          dvc pull train@ae_conv
          dvc repro train@ae_conv
          dvc push train@ae_conv

      - name: report_conv
        run: |
          scripts/autoencoder_report.sh autoencoder conv >> report.md
          cml-send-github-check report.md 

      - name: train_vae_dense
        run: |
          dvc pull train@vae_dense
          dvc repro train@vae_dense
          dvc push train@vae_dense

      - name: report_vae_dense
        run: |
          scripts/autoencoder_report.sh vae dense >> report.md
          cml-send-github-check report.md 

      - name: train_vae_conv
        run: |
          dvc pull train@vae_conv
          dvc repro train@vae_conv
          dvc push train@vae_conv

      - name: report_conv
        run: |
          scripts/autoencoder_report.sh vae conv >> report.md
          cml-send-github-check report.md 

