# This is a basic workflow to help you get started with Actions

name: AE

# Controls when the action will run. 
on:
  push:
    #branches: [ main ]
  pull_request:
    #branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted,gpu]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: requirements
        run: pip install -r requirements.txt

      - name: pull_data
        run: dvc pull data/external/sprites.dvc

      - name: train_conv_ae
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          dvc pull ae_conv_train
          dvc repro ae_conv_train
          dvc push ae_conv_train

      - name: report_conv
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "# Conv Autoencoder" >> report.md
          scripts/autoencoder_report.sh conv >> report.md

          echo "## Generated" >> report.md
          cml-publish --md 'reports/autoencoder/conv/gen.gif' >> report.md
          cml-send-github-check report.md 

      # Dense
      - name: train_dense_ae
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          dvc pull ae_dense_train
          dvc repro ae_dense_train
          dvc push ae_dense_train

      - name: report_dense
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "# Dense Autoencoder" >> report.md
          scripts/autoencoder_report.sh dense >> report.md

          echo "## Generated" >> report.md
          cml-publish --md 'reports/autoencoder/dense/gen.gif' >> report.md
          cml-send-github-check report.md 

