name: Build Docker Images

on:
  push:
    paths:
      - '*Dockerfile'
      - 'requirements.txt'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
      - 
        name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push CI/CD Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: cicd.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pokegen:cicd